version: "1"
name: computeshare-server
stages:
  init:
    steps:
#      - name: git clone
#        uses: git-checkout
#        with:
#          url: https://github.com/mohaijiang/computeshare-server.git
#          branch: main
        - name: wokdir
          uses: workdir
          with:
            workdir: /Users/mohaijiang/IdeaProjects/blockchain/computeshare-server
  build:
    needs:
      - init
    steps:
      - name: build
        run: |
          make generate
          docker buildx build -t hamstershare/computeshare-server:${PIPELINE_ID} --platform=linux/amd64 --push .

  deploy:
    needs:
      - init
    steps:
      - name: deploy
        run: |
          envsubst < k8s.yml | kubectl -n computeshare apply -f -

