apiVersion: apps/v1
kind: Deployment
metadata:
  name: computeshare-server
  labels:
    app: computeshare-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computeshare-server
  template:
    metadata:
      labels:
        app: computeshare-server
    spec:
      containers:
        - name: computeshare-server
          image: hamstershare/computeshare-server:${PIPELINE_ID}
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9000
              name: grpc
          volumeMounts:
            - mountPath: /data/conf
              name: config
      volumes:
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: config
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "config.yaml"
                path: "config.yaml"
---