server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9009
    timeout: 10s
  p2p:
    port: 4002
    swarm_key: |
      /key/swarm/psk/1.0.0/
      /base16/
      55158d9b6b7e5a8e41aa8b34dd057ff1880e38348613d27ae194ad7c5b9670d7
    bootstraps:
      - "/ip4/34.139.126.73/tcp/4001/p2p/12D3KooWRsKNAgbGaQkVbbzg5xEw2FtvPRF7MiYtmRvFPYegNVnu"
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/computeshare?charset=utf8&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s
  ipfs:
    url: 127.0.0.1:5001

auth:
  service_key: some-secret-key
  api_key: some-secret-key-for-forntend

dispose:
  s3:
    target_docker_host: unix:///var/run/docker.sock
    target_docker_container_name: seaweedfs-master-1
    endpoint: http://127.0.0.1:8333
    region: shanghai
    s3_url_prefix: s3://
    url_prefix: http://127.0.0.1:8333/